image: nixos/nix:latest

stages:
  - deploy

pages:
  stage: deploy
  script:
    - export NIXPKGS_REV="$(nix-instantiate --eval --expr 'let lock = builtins.fromJSON (builtins.readFile ./flake.lock); in lock.nodes.nixpkgs.locked.rev' | tr -d '"')"
    - export NIX_PATH="nixpkgs=https://github.com/NixOS/nixpkgs/archive/${NIXPKGS_REV}.tar.gz"
    - nix-build -A docs.html
    - mkdir public
    - cp -r ./result/share/doc/home-manager/* public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: always
