{
  config,
  lib,
  pkgs,
  ...
}:
let
  inherit (lib)
    literalExpression
    mkEnableOption
    mkOption
    optionalString
    types
    ;
  cfg = config.programs.sketchybar;

  # Function to create Lua inline expressions
  mkLuaInline = expr: {
    _type = "lua-inline";
    inherit expr;
  };

  toSketchybarConfig =
    opts:
    let
      keyValuePairs = lib.mapAttrsToList (p: v: "${p}=${toString v}") opts;
      lastPair = lib.lists.last keyValuePairs;
      linesWithQuotes = map (pair: ''
        ${pair} \
      '') (lib.lists.init keyValuePairs);
      lastLine = "${lastPair}";
    in
    lib.concatStrings (linesWithQuotes ++ [ lastLine ]);

  exportVariables =
    variables:
    lib.concatStringsSep "\n" (
      lib.mapAttrsToList (name: value: "export ${name}=${value}") variables
    );

  generateSourceLines =
    sources:
    let
      generateCommand =
        source:
        if (lib.isAttrs source) then
          let
            name = source.name;
            placement = source.placement;
            remainingAttrs = removeAttrs source [ "name" "placement" ];
            keyValuePairs = lib.concatStringsSep " " (
              lib.mapAttrsToList (key: value: "${key}=${toString value}") remainingAttrs
            );
          in
          "sketchybar --add item ${name} ${placement} --set ${name} ${keyValuePairs}"
        else if (lib.isString source || lib.isPath source) then
          "source " + toString source
        else
          throw "Unsupported source type";
    in
    lib.concatStringsSep "\n" (map generateCommand sources);

  # Generate Lua config file using lib.generators.toLua
  generateLuaConfig =
    cfg:
    let
      # Convert Nix variables to Lua variables
      variablesAttrs = lib.mapAttrs (name: value: value) cfg.variables;

      # Prepare the configuration
      config = {
        # Configuration sections
        bar = cfg.config.bar;
        defaults = cfg.config.defaults;
        # User variables
        variables = variablesAttrs;
      };
    in
    ''
      #!/usr/bin/env lua
      -- Generated by home-manager
      local sbar = require("sbarlua")

      -- Set variables
      ${optionalString (cfg.variables != { }) (
        lib.concatStringsSep "\n" (
          lib.mapAttrsToList (
            name: value: "sbar.variables[${lib.generators.toLua { } name}] = ${lib.generators.toLua { } value}"
          ) cfg.variables
        )
      )}

      -- Configure bar
      ${optionalString (cfg.config.bar != { }) "sbar.bar:set(${lib.generators.toLua { } cfg.config.bar})"}

      -- Configure defaults
      ${optionalString (cfg.config.defaults != { })
        "sbar.defaults:set(${lib.generators.toLua { } cfg.config.defaults})"
      }

      -- Extra configuration
      ${cfg.extraConfig}

      -- Update the bar
      sbar:update()
    '';

  bashConfig = pkgs.writeTextFile {
    name = "sketchybarrc";
    text = (
      optionalString (cfg.sources != [ ]) ''
        ${generateSourceLines cfg.sources}

      ''
      + optionalString (cfg.variables != { }) ''
        ${exportVariables cfg.variables}

      ''
      + optionalString (cfg.config.bar != { }) ''
        sketchybar --bar \
        ${toSketchybarConfig cfg.config.bar}

      ''
      + optionalString (cfg.config.defaults != { }) ''
        sketchybar --default \
        ${toSketchybarConfig cfg.config.defaults}

      ''
      + optionalString (cfg.plugins != [ ]) ''

        ${generateSourceLines cfg.plugins}

      ''
      + optionalString (cfg.extraConfig != "") ("\n" + cfg.extraConfig + "\n")
      + ''

        sketchybar --update''
    );
    executable = true;
  };

  luaConfig = pkgs.writeTextFile {
    name = "sketchybarrc.lua";
    text = generateLuaConfig cfg;
    executable = true;
  };

  configFile = if cfg.configType == "bash" then bashConfig else luaConfig;
in
{
  options = {
    programs.sketchybar = {
      enable = mkEnableOption "sketchybar";

      package = mkOption {
        type = types.package;
        default = pkgs.sketchybar;
        defaultText = literalExpression "pkgs.sketchybar";
        example = literalExpression "pkgs.sketchybar";
        description = "The sketchybar package to install";
      };

      configType = mkOption {
        type = types.enum [
          "bash"
          "lua"
        ];
        default = "bash";
        description = ''
          The type of configuration to generate.

          Set to "bash" to use the standard bash configuration.
          Set to "lua" to use the Lua configuration via SbarLua.
        '';
      };

      sbarLuaPackage = mkOption {
        type = types.nullOr types.package;
        default = null;
        defaultText = literalExpression "null";
        example = literalExpression "pkgs.sbarlua";
        description = ''
          The SbarLua package to install. Required when configType is set to "lua".
        '';
      };

      extraConfig = mkOption {
        type = types.lines;
        default = "";
        description = ''
          Additional configuration code to add to the config file.
          Format should match the selected configType:
          - For bash: shell script commands to run
          - For lua: lua code to execute
        '';
      };

      sources = mkOption {
        type = with lib.types; listOf (either path str);
        default = [ ];
        example = literalExpression "[]";
        description = "The sources to fetch and install for bash configuration.";
      };

      plugins = mkOption {
        type = with lib.types; listOf (either (either path str) attrs);
        default = [ ];
        example = literalExpression ''
          [
            "script.sh"
            { name = "script";
              placement = "right";
            }
          ]'';
        description = "The plugins to add for bash configuration.";
      };

      variables = mkOption {
        type = types.attrs;
        default = { };
        example = literalExpression ''
          {
            TEXT = "0xffcad3f5";
          }
        '';
        description = lib.mdDoc ''
          Key/Value pairs of environment variables to export via the configuration file.
          Used in both bash and lua configuration.
        '';
      };

      config = mkOption {
        description = lib.mdDoc ''
          Sketchybar config options to generate sketchybarrc.
          Used in both bash and lua configuration modes.
        '';
        type = types.submodule {
          options = {
            bar = mkOption {
              type = types.attrs;
              default = { };
              example = literalExpression ''
                {
                  blur_radius         = 30;
                  border_width        = 2;
                  color               = "red";
                  corner_radius       = 9;
                  height              = 40;
                  margin              = 10;
                  notch_width         = 0;
                  padding_left        = 18;
                  padding_right       = 10;
                  position            = "top";
                  shadow              = "on";
                  sticky              = "on";
                  topmost             = "off";
                  y_offset            = 10;
                }
              '';
              description = lib.mdDoc ''
                Key/Value pairs to pass to sketchybar --bar command (bash) or sbar.bar:set() (lua).
              '';
            };

            defaults = mkOption {
              type = types.attrs;
              default = { };
              example = literalExpression ''
                {
                  "icon.color" = "$TEXT";
                  "icon.font" = "$NERD_FONT:Bold:16.0";
                  "icon.padding_left" = "$PADDINGS";
                  "icon.padding_right" = "$PADDINGS";
                  "label.color" = "$TEXT";
                  "label.font" = "$FONT:Semibold:13.0";
                  "label.padding_left" = "$PADDINGS";
                  "label.padding_right" = "$PADDINGS";
                  "background.corner_radius" = 9;
                  "background.height" = 30;
                  "background.padding_left" = "$PADDINGS";
                  "background.padding_right" = "$PADDINGS";
                  "popup.height" = 30;
                  "popup.horizontal" = "false";
                  "popup.background.border_color" = "$BLUE";
                  "popup.background.border_width" = 2;
                  "popup.background.color" = "$MANTLE";
                  "popup.background.corner_radius" = 11;
                  "popup.background.shadow.drawing" = "on";
                }
              '';
              description = lib.mdDoc ''
                Key/Value pairs to pass to sketchybar --defaults command (bash) or sbar.defaults:set() (lua).
              '';
            };
          };
        };
      };

      # Service integration options
      service = {
        enable = mkEnableOption "sketchybar service";

        package = mkOption {
          type = types.nullOr types.package;
          default = null;
          defaultText = literalExpression "config.programs.sketchybar.package";
          description = ''
            The sketchybar package to use for the service.
            If null, uses the same package as programs.sketchybar.package.
          '';
        };

        errorLogFile = mkOption {
          type = with lib.types; nullOr (either path str);
          default = "${config.home.homeDirectory}/Library/Logs/sketchybar/sketchybar.err.log";
          defaultText = lib.literalExpression "\${config.home.homeDirectory}/Library/Logs/sketchybar/sketchybar.err.log";
          example = "/Users/khaneliman/Library/Logs/sketchybar.log";
          description = "Absolute path to log all stderr output.";
        };

        outLogFile = mkOption {
          type = with lib.types; nullOr (either path str);
          default = "${config.home.homeDirectory}/Library/Logs/sketchybar/sketchybar.out.log";
          defaultText = lib.literalExpression "\${config.home.homeDirectory}/Library/Logs/sketchybar/sketchybar.out.log";
          example = "/Users/khaneliman/Library/Logs/sketchybar.log";
          description = "Absolute path to log all stdout output.";
        };

        extraPackages = mkOption {
          type = with lib.types; listOf package;
          default = [ ];
          example = literalExpression "[ pkgs.jq ]";
          description = ''
            Extra packages to add to PATH for the sketchybar service.
          '';
        };
      };
    };
  };

  config = lib.mkMerge [
    (lib.mkIf cfg.enable {
      home.packages = [
        cfg.package
      ] ++ lib.optional (cfg.configType == "lua" && cfg.sbarLuaPackage != null) cfg.sbarLuaPackage;

      assertions = [
        {
          assertion = !(cfg.configType == "lua" && cfg.sbarLuaPackage == null);
          message = "When configType is set to \"lua\", sbarLuaPackage must be specified";
        }
      ];

      xdg.configFile."sketchybar/sketchybarrc".source = configFile;
    })

    (lib.mkIf cfg.service.enable {
      assertions = [
        (lib.hm.assertions.assertPlatform "programs.sketchybar.service" pkgs lib.platforms.darwin)
      ];

      launchd.agents.sketchybar = {
        enable = true;
        config = {
          Program = lib.getExe (if cfg.service.package != null then cfg.service.package else cfg.package);
          ProcessType = "Interactive";
          KeepAlive = true;
          RunAtLoad = true;
          StandardErrorPath = cfg.service.errorLogFile;
          StandardOutPath = cfg.service.outLogFile;
          EnvironmentVariables = {
            PATH = (
              lib.concatMapStringsSep ":" (p: "${p}/bin") (
                (if cfg.service.package != null then [ cfg.service.package ] else [ cfg.package ])
                ++ lib.optional (cfg.configType == "lua" && cfg.sbarLuaPackage != null) cfg.sbarLuaPackage
                ++ cfg.service.extraPackages
              )
            );
          };
        };
      };
    })
  ];
}
