{ config, ... }:

{
  config = {
    programs.librewolf = {
      enable = true;
      settings = {
        "webgl.disabled" = false;
        "privacy.resistFingerprinting" = false;
        "network.cookie.cookieBehavior" = 1;
        "browser.startup.homepage" = "https://example.com";
        "dom.security.https_only_mode" = true;
        "extensions.blocklist.enabled" = false;
      };
    };

    test.stubs.librewolf = { };

    nmt.script = ''
      # Test that LibreWolf package is installed
      assertFileExists home-path/bin/librewolf

      # Test that settings overrides file is created
      assertFileExists home-files/.librewolf/librewolf.overrides.cfg

      # Test that the overrides file contains the correct settings
      assertFileContains home-files/.librewolf/librewolf.overrides.cfg \
        'defaultPref("webgl.disabled", false);'

      assertFileContains home-files/.librewolf/librewolf.overrides.cfg \
        'defaultPref("privacy.resistFingerprinting", false);'

      assertFileContains home-files/.librewolf/librewolf.overrides.cfg \
        'defaultPref("network.cookie.cookieBehavior", 1);'

      assertFileContains home-files/.librewolf/librewolf.overrides.cfg \
        'defaultPref("browser.startup.homepage", "https://example.com");'

      assertFileContains home-files/.librewolf/librewolf.overrides.cfg \
        'defaultPref("dom.security.https_only_mode", true);'

      assertFileContains home-files/.librewolf/librewolf.overrides.cfg \
        'defaultPref("extensions.blocklist.enabled", false);'

      # Test that the file header is present
      assertFileContains home-files/.librewolf/librewolf.overrides.cfg \
        "// Generated by Home Manager."
    '';
  };
}
