{
  home.preferXdgDirectories = true;

  programs.readline = {
    enable = true;
    variables.bell-style = "audible";
  };

  nmt.script = ''
    assertFileExists home-files/.config/inputrc
    assertFileContent \
      home-files/.config/inputrc \
      ${builtins.toFile "readline-expected" ''
        # Generated by Home Manager.

        $include /etc/inputrc
        set bell-style audible

      ''}

    assertFileExists home-path/etc/profile.d/hm-session-vars.sh
    assertFileContains \
      home-path/etc/profile.d/hm-session-vars.sh \
      'export INPUTRC="/home/hm-user/.config/inputrc"'
  '';
}
